import type { Song } from "@/stores/searchStore";
import { mockArtwork } from "@/lib/artwork";

export const MOCK_SONGS: Song[] = [
  {
    id: "1",
    title: "Blinding Lights",
    artist: "The Weeknd",
    album: "After Hours",
    year: 2020,
    duration: 200,
    plays: 948211,
    artwork: mockArtwork("Blinding Lights"),
  },
  {
    id: "2",
    title: "Shape of You",
    artist: "Ed Sheeran",
    album: "÷ (Divide)",
    year: 2017,
    duration: 234,
    plays: 911423,
    artwork: mockArtwork("Shape of You"),
  },
  {
    id: "3",
    title: "Perfect",
    artist: "Ed Sheeran",
    album: "÷ (Divide)",
    year: 2017,
    duration: 263,
    plays: 768530,
    artwork: mockArtwork("Perfect"),
  },
  {
    id: "4",
    title: "Die With A Smile",
    artist: "Bruno Mars & Lady Gaga",
    album: "Die With A Smile (Single)",
    year: 2024,
    duration: 251,
    plays: 654882,
    artwork: mockArtwork("Die With A Smile"),
  },
  {
    id: "5",
    title: "Cruel Summer",
    artist: "Taylor Swift",
    album: "Lover",
    year: 2019,
    duration: 178,
    plays: 590144,
    artwork: mockArtwork("Cruel Summer"),
  },
  {
    id: "6",
    title: "APT.",
    artist: "ROSÉ & Bruno Mars",
    album: "rosie",
    year: 2024,
    duration: 196,
    plays: 487905,
    artwork: mockArtwork("APT."),
  },
  {
    id: "7",
    title: "Espresso",
    artist: "Sabrina Carpenter",
    album: "Short n' Sweet",
    year: 2024,
    duration: 175,
    plays: 412633,
    artwork: mockArtwork("Espresso"),
  },
  {
    id: "8",
    title: "Someone Like You",
    artist: "Adele",
    album: "21",
    year: 2011,
    duration: 285,
    plays: 401872,
    artwork: mockArtwork("Someone Like You"),
  },
  {
    id: "9",
    title: "Love Story",
    artist: "Taylor Swift",
    album: "Fearless",
    year: 2008,
    duration: 235,
    plays: 378920,
    artwork: mockArtwork("Love Story"),
  },
  {
    id: "10",
    title: "Stay",
    artist: "The Kid LAROI & Justin Bieber",
    album: "F*CK LOVE 3: OVER YOU",
    year: 2021,
    duration: 141,
    plays: 355411,
    artwork: mockArtwork("Stay"),
  },
  {
    id: "11",
    title: "A Thousand Miles",
    artist: "Vanessa Carlton",
    album: "Be Not Nobody",
    year: 2002,
    duration: 236,
    plays: 332144,
    artwork: mockArtwork("A Thousand Miles"),
  },
  {
    id: "12",
    title: "Don't Stop Believin'",
    artist: "Journey",
    album: "Escape",
    year: 1981,
    duration: 251,
    plays: 307688,
    artwork: mockArtwork("Don't Stop Believin'"),
  },
  {
    id: "13",
    title: "Bohemian Rhapsody",
    artist: "Queen",
    album: "A Night at the Opera",
    year: 1975,
    duration: 354,
    plays: 298566,
    artwork: mockArtwork("Bohemian Rhapsody"),
  },
  {
    id: "14",
    title: "Sweet Caroline",
    artist: "Neil Diamond",
    album: "Sweet Caroline",
    year: 1969,
    duration: 224,
    plays: 210093,
    artwork: mockArtwork("Sweet Caroline"),
  },
  {
    id: "15",
    title: "I Will Always Love You",
    artist: "Whitney Houston",
    album: "The Bodyguard",
    year: 1992,
    duration: 271,
    plays: 198732,
    artwork: mockArtwork("I Will Always Love You"),
  },
  {
    id: "16",
    title: "Let It Go",
    artist: "Idina Menzel",
    album: "Frozen",
    year: 2013,
    duration: 225,
    plays: 176490,
    artwork: mockArtwork("Let It Go"),
  },
  {
    id: "17",
    title: "Shallow",
    artist: "Lady Gaga & Bradley Cooper",
    album: "A Star Is Born",
    year: 2018,
    duration: 216,
    plays: 165233,
    artwork: mockArtwork("Shallow"),
  },
  {
    id: "18",
    title: "Hotel California",
    artist: "Eagles",
    album: "Hotel California",
    year: 1976,
    duration: 391,
    plays: 154891,
    artwork: mockArtwork("Hotel California"),
  },
];

export const MOCK_LYRICS = [
  { time: 6, text: "I found a love for me" },
  { time: 11, text: "Darling just dive right in" },
  { time: 15, text: "And follow my lead" },
  { time: 20, text: "I found a girl, beautiful and sweet" },
  { time: 25, text: "Oh, I never knew you were the somebody waiting for me" },
  { time: 31, text: "'Cause we were just kids when we fell in love" },
  { time: 36, text: "Not knowing what it was" },
  { time: 40, text: "I will not give you up this time" },
  { time: 45, text: "But darling, just kiss me slow" },
  { time: 50, text: "Your heart is all I own" },
];